spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://inventory-management-db/INVENTORY_DB?createDatabaseIfNotExist=true
    username: intAdmin
    password: intAdmin.123
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect